const STATIC_TRIMS: Record<string, Record<string, string[]>> = {
  acura: {
    "ilx": ["Premium","Technology","A-Spec Technology","Technology A-Spec"],
    "integra": ["Standard","A-Spec","A-Spec Technology","Type S"],
    "mdx": ["Standard","Technology","A-Spec","A-Spec Technology","Advance","Type S","Type S Advance"],
    "rdx": ["Standard","Technology","A-Spec","A-Spec Technology","Advance","PMC Edition"],
    "tlx": ["Standard","Technology","A-Spec Technology","Advance","Type S","Type S Advance","PMC Edition"],
  },
  audi: {
    "a3": ["Premium","Premium Plus","Prestige"],
    "a4": ["Premium","Premium Plus","Prestige","Black Edition"],
    "a5": ["Premium","Premium Plus","Prestige"],
    "a6": ["Premium","Premium Plus","Prestige"],
    "a7": ["Premium","Premium Plus","Prestige"],
    "a8": ["Standard","L","L Sport","L 60 TFSI e"],
    "e-tron": ["Premium","Premium Plus","Prestige"],
    "q3": ["Premium","Premium Plus","Prestige","S line Premium","S line Premium Plus","S line Prestige"],
    "q5": ["Premium","Premium Plus","Prestige","S line Premium","S line Premium Plus","S line Prestige"],
    "q7": ["Premium","Premium Plus","Prestige"],
    "q8": ["Premium","Premium Plus","Prestige"],
    "rs3": ["Standard"],
    "rs5": ["Sportback","Coupe"],
    "rs7": ["Standard"],
    "s3": ["Premium","Premium Plus","Prestige"],
    "s4": ["Premium","Premium Plus","Prestige"],
    "s5": ["Premium","Premium Plus","Prestige"],
    "tt": ["Standard","S"],
  },
  bmw: {
    "2 series": ["230i","230i xDrive","M240i","M240i xDrive"],
    "3 series": ["330i","330i xDrive","330e","330e xDrive","M340i","M340i xDrive"],
    "4 series": ["430i","430i xDrive","430i Gran Coupe","M440i","M440i xDrive","M440i Gran Coupe"],
    "5 series": ["530i","530i xDrive","530e","530e xDrive","540i","540i xDrive","M550i xDrive"],
    "7 series": ["740i","740i xDrive","750i xDrive","760i xDrive","Alpina B7"],
    "8 series": ["840i","840i xDrive","840i Gran Coupe","M850i xDrive","Alpina B8"],
    "x1": ["sDrive28i","xDrive28i"],
    "x2": ["sDrive28i","xDrive28i","M35i"],
    "x3": ["sDrive30i","xDrive30i","xDrive30e","M40i"],
    "x4": ["xDrive30i","M40i"],
    "x5": ["sDrive40i","xDrive40i","xDrive45e","M50i","M50d"],
    "x6": ["sDrive40i","xDrive40i","M50i"],
    "x7": ["xDrive40i","xDrive50i","M60i","Alpina XB7"],
    "m2": ["Standard","Competition"],
    "m3": ["Standard","Competition","Competition xDrive","CS"],
    "m4": ["Standard","Competition","Competition xDrive","CS","CSL"],
    "m5": ["Standard","Competition","CS"],
    "m8": ["Standard","Competition","Gran Coupe","Competition Gran Coupe"],
    "ix": ["xDrive50","M60"],
    "i4": ["eDrive35","eDrive40","M50"],
    "i7": ["xDrive60","M70"],
  },
  buick: {
    "enclave": ["Preferred","Essence","Avenir","Sport Touring"],
    "encore": ["Preferred","Select","Sport Touring","Essence"],
    "encore gx": ["Preferred","Select","Essence","Sport Touring","Avenir"],
    "envision": ["Preferred","Essence","Avenir","Sport Touring"],
    "lacrosse": ["Preferred","Essence","Avenir"],
  },
  cadillac: {
    "ct4": ["Luxury","Premium Luxury","V-Series","V-Series Blackwing"],
    "ct5": ["Luxury","Premium Luxury","Premium Luxury V8","V-Series","V-Series Blackwing"],
    "escalade": ["Luxury","Premium Luxury","Sport","Sport Platinum","Platinum","ESV Luxury","ESV Premium Luxury","ESV Sport","ESV Platinum"],
    "lyriq": ["Luxury","Luxury 2","Sport 1","Sport 2","Sport 3"],
    "xt4": ["Luxury","Premium Luxury","Sport"],
    "xt5": ["Luxury","Premium Luxury","Sport","Platinum"],
    "xt6": ["Luxury","Premium Luxury","Sport","Platinum"],
  },
  chevrolet: {
    "blazer": ["LT","RS","Premier","SS"],
    "camaro": ["LS","LT","LT1","SS","ZL1","ZL1 1LE"],
    "colorado": ["WT","LT","Z71","Trail Boss","ZR2","ZR2 Bison"],
    "corvette": ["Stingray","Stingray 3LT","Z06","Z06 3LZ","E-Ray","ZR1"],
    "equinox": ["LS","LT","RS","Premier","EV"],
    "express": ["LS","LT"],
    "malibu": ["LS","RS","LT","Premier"],
    "silverado 1500": ["WT","Custom","Custom Trail Boss","LT","LT Trail Boss","RST","LTZ","High Country","ZR2"],
    "silverado 2500hd": ["WT","Custom","LT","LTZ","High Country"],
    "silverado 3500hd": ["WT","Custom","LT","LTZ","High Country"],
    "suburban": ["LS","LT","RST","Z71","Premier","High Country"],
    "tahoe": ["LS","LT","RST","Z71","Premier","High Country"],
    "trailblazer": ["LS","LT","ACTIV","RS","Premier"],
    "traverse": ["LS","LT","RS","Premier","High Country"],
    "trax": ["LS","LT","ACTIV","RS","Premier"],
  },
  chrysler: {
    "300": ["Touring","Touring L","S","C","C Platinum","300C"],
    "pacifica": ["Touring","Touring L","Touring Plus","Pinnacle","Limited","Limited S","Hybrid Touring Plus","Hybrid Pinnacle"],
    "voyager": ["LX","Limited"],
  },
  dodge: {
    "challenger": ["SXT","GT","R/T","R/T Scat Pack","R/T Scat Pack Widebody","SRT Hellcat","SRT Hellcat Redeye","SRT Hellcat Redeye Widebody","SRT Super Stock","SRT Demon","Last Call"],
    "charger": ["SXT","GT","R/T","R/T Scat Pack","Daytona","SRT Hellcat","SRT Hellcat Redeye","SRT Hellcat Redeye Widebody","Super Bee"],
    "durango": ["SXT","GT","Citadel","R/T","SRT 392","SRT Hellcat","Pursuit"],
    "hornet": ["GT","GT Plus","R/T","R/T Plus","GLH"],
  },
  ford: {
    "bronco": ["Base","Big Bend","Black Diamond","Outer Banks","Badlands","Wildtrak","Everglades","Raptor","Heritage","Heritage Limited"],
    "bronco sport": ["Base","Big Bend","Outer Banks","Badlands","Heritage","Heritage Limited"],
    "edge": ["SE","SEL","ST","ST-Line","Titanium"],
    "escape": ["S","SE","SEL","Titanium","ST-Line","ST-Line Elite","Plug-In Hybrid SE","Plug-In Hybrid Titanium"],
    "expedition": ["XL","XLT","Limited","King Ranch","Platinum","Timberline","Max XLT","Max Limited","Max King Ranch","Max Platinum","Max Timberline"],
    "explorer": ["Base","XLT","ST","Timberline","Limited","Limited Hybrid","King Ranch","Platinum","Platinum Hybrid","ST-Line","Endeavor"],
    "f-150": ["XL","XLT","Lariat","King Ranch","Platinum","Limited","Raptor","Raptor R","Tremor","Lightning Pro","Lightning XLT","Lightning Lariat","Lightning Platinum","Lightning Black Ops"],
    "f-250 super duty": ["XL","XLT","Lariat","King Ranch","Platinum","Limited","Tremor"],
    "f-350 super duty": ["XL","XLT","Lariat","King Ranch","Platinum","Limited","Tremor"],
    "maverick": ["XL","XLT","Lariat","Tremor"],
    "mustang": ["EcoBoost","EcoBoost Premium","GT","GT Premium","Mach 1","Shelby GT350","Shelby GT350R","Shelby GT500","Dark Horse","Dark Horse Premium"],
    "mustang mach-e": ["Select","Premium","California Route 1","GT","Rally"],
    "ranger": ["XL","XLT","Lariat","Tremor","Raptor"],
  },
  genesis: {
    "g70": ["Standard","2.0T","2.0T Advanced","3.3T","3.3T Advanced","3.3T Sport"],
    "g80": ["Standard","2.5T","2.5T Advanced","3.5T","3.5T Advanced","Sport 2.5T","Sport 3.5T","Electrified"],
    "g90": ["Standard","3.3T","3.3T Premium","5.0 Ultimate","Electrified","Electrified Premium"],
    "gv70": ["Standard","2.5T","2.5T Advanced","3.5T","3.5T Advanced","Sport 2.5T","Sport 3.5T","Electrified","Electrified Advanced"],
    "gv80": ["Standard","2.5T","2.5T Advanced","3.5T","3.5T Advanced"],
  },
  gmc: {
    "acadia": ["SLE","SLT","AT4","Denali","Denali Ultimate"],
    "canyon": ["Elevation","AT4","AT4X","Denali","Denali Ultimate"],
    "sierra 1500": ["Pro","SLE","SLT","Elevation","AT4","AT4X","Denali","Denali Ultimate"],
    "sierra 2500hd": ["Pro","SLE","SLT","AT4","Denali"],
    "sierra 3500hd": ["Pro","SLE","SLT","AT4","Denali"],
    "terrain": ["SLE","SLT","AT4","Denali"],
    "yukon": ["SLE","SLT","AT4","Denali","Denali Ultimate","XL SLE","XL SLT","XL AT4","XL Denali","XL Denali Ultimate"],
  },
  honda: {
    "accord": ["LX","Sport","Sport Hybrid","EX","EX-L","Touring","Hybrid EX-L","Hybrid Touring","Sport-L"],
    "civic": ["LX","Sport","EX","EX-L","Touring","Si","Type R","Hatchback Sport","Hatchback EX-L","Hatchback Touring"],
    "cr-v": ["LX","EX","EX-L","Sport","Sport-L","Touring","Sport Hybrid","Sport-L Hybrid","Touring Hybrid"],
    "hr-v": ["LX","Sport","EX","EX-L"],
    "odyssey": ["LX","EX","EX-L","Touring","Elite"],
    "passport": ["Sport","EX-L","TrailSport","Touring","Elite"],
    "pilot": ["LX","Sport","EX-L","TrailSport","Touring","Elite","Black Edition"],
    "prologue": ["EX","EX-L","Touring","Elite"],
    "ridgeline": ["Sport","RTL","RTL-E","Black Edition"],
  },
  hyundai: {
    "elantra": ["SE","SEL","N Line","Limited","N"],
    "ioniq 5": ["SE Standard Range","SE","SEL","Limited","N"],
    "ioniq 6": ["SE Standard Range","SE","SEL","Limited"],
    "kona": ["SE","SEL","N Line","Limited","N","Electric SE","Electric SEL","Electric Limited"],
    "nexo": ["Blue","Limited"],
    "palisade": ["SE","SEL","XRT","Limited","Calligraphy"],
    "santa cruz": ["SE","SEL","Sport","Limited","XRT"],
    "santa fe": ["SE","SEL","XRT","Limited","Calligraphy","Plug-In Hybrid SEL","Plug-In Hybrid Limited","Plug-In Hybrid Calligraphy"],
    "sonata": ["SE","SEL","SEL Plus","N Line","Limited"],
    "tucson": ["SE","SEL","XRT","N Line","Limited","Plug-In Hybrid SE","Plug-In Hybrid SEL","Plug-In Hybrid N Line","Plug-In Hybrid Limited"],
    "venue": ["SE","SEL","Limited"],
  },
  infiniti: {
    "q50": ["Pure","Luxe","Sensory","Red Sport 400","Silver Sport"],
    "q60": ["Pure","Luxe","Sensory","Red Sport 400","Silver Sport"],
    "qx50": ["Pure","Luxe","Sensory","Autograph"],
    "qx55": ["Pure","Luxe","Sensory","Autograph"],
    "qx60": ["Pure","Luxe","Sensory","Autograph"],
    "qx80": ["Luxe","Sensory","Autograph","Autograph Edition"],
  },
  jeep: {
    "cherokee": ["Latitude","Latitude Lux","Trailhawk","Limited","Altitude","High Altitude"],
    "compass": ["Sport","Latitude","Latitude Lux","Trailhawk","Limited","High Altitude"],
    "gladiator": ["Sport","Sport S","Willys Sport","Willys","Overland","High Altitude","Rubicon","Mojave"],
    "grand cherokee": ["Laredo","Laredo X","Altitude","Limited","Trailhawk","Overland","Summit","Summit Reserve","SRT","Trackhawk","4xe Trailhawk","4xe Overland","4xe Summit","4xe Summit Reserve","L Laredo","L Limited","L Overland","L Summit","L Summit Reserve"],
    "renegade": ["Sport","Latitude","Trailhawk","Limited","High Altitude"],
    "wagoneer": ["Series I","Series II","Series III"],
    "grand wagoneer": ["Series I","Series II","Series III","Obsidian"],
    "wrangler": ["Sport","Sport S","Willys Sport","Willys","Sahara","Freedom","Rubicon","Rubicon 392","High Altitude","4xe Sport S","4xe Willys","4xe Sahara","4xe Rubicon","Unlimited Sport","Unlimited Sport S","Unlimited Willys","Unlimited Sahara","Unlimited Rubicon","Unlimited Rubicon 392","Unlimited High Altitude","Unlimited 4xe"],
  },
  kia: {
    "carnival": ["LX","LX+","EX","SX","SX Prestige"],
    "ev6": ["Light","Wind","GT-Line","GT"],
    "ev9": ["Light","Wind","GT-Line","GT"],
    "k5": ["LX","GT-Line","EX","GT"],
    "niro": ["LX","EX","SX Touring","EV LX","EV EX","EV EX Premium","EV Wave","EV Wind","EV GT-Line","Plug-In Hybrid LX","Plug-In Hybrid EX","Plug-In Hybrid EX Premium","Plug-In Hybrid SX Touring"],
    "seltos": ["LX","S","EX","SX","SX Turbo","Nightfall","X-Line"],
    "sorento": ["LX","S","EX","SX","SX Prestige","X-Line EX","X-Line SX Prestige","Plug-In Hybrid EX","Plug-In Hybrid SX","Plug-In Hybrid SX Prestige"],
    "sportage": ["LX","EX","SX Turbo","X-Line","X-Line Pro","Plug-In Hybrid EX","Plug-In Hybrid SX"],
    "stinger": ["Standard","GT-Line","GT1","GT2","GT Elite"],
    "telluride": ["LX","S","EX","SX","SX Prestige","SX-P","X-Line EX","X-Line SX Prestige","X-Pro SX Prestige"],
  },
  land_rover: {
    "defender": ["90 Standard","90 S","90 SE","90 X-Dynamic SE","90 X","90 First Edition","110 Standard","110 S","110 SE","110 X-Dynamic SE","110 X","110 First Edition","130 SE","130 X","130 Outbound"],
    "discovery": ["S","SE","R-Dynamic SE","HSE","R-Dynamic HSE","Metropolitan Edition"],
    "discovery sport": ["S","SE","R-Dynamic SE","HSE","R-Dynamic HSE"],
    "range rover": ["Standard","SE","HSE","Autobiography","SV","Fifty","SV Autobiography"],
    "range rover evoque": ["S","SE","R-Dynamic SE","HSE","R-Dynamic HSE","Bronze Collection"],
    "range rover sport": ["S","SE","Dynamic SE","HSE","Dynamic HSE","Autobiography","SV"],
    "range rover velar": ["S","SE","R-Dynamic SE","HSE","R-Dynamic HSE","SVAutobiography Dynamic"],
  },
  lexus: {
    "es": ["250","300h","350","350 F Sport","350 F Sport Handling","350 Ultra Luxury"],
    "gx": ["Premium","Luxury","Overtrail","Overtrail+","Luxury+"],
    "is": ["300","300 F Sport","350","350 F Sport"],
    "lc": ["500","500 Convertible","500h","500h Convertible"],
    "ls": ["500","500 F Sport","500h","500h F Sport"],
    "lx": ["350","600h L"],
    "nx": ["250","250h","350","350h","350h F Sport Handling","450h+"],
    "rc": ["350","350 F Sport","F"],
    "rx": ["350","350 F Sport Handling","350h","500h","500h F Sport Handling"],
    "tx": ["350","350h","500h","500h F Sport Handling"],
    "ux": ["200","200 F Sport","250h","250h F Sport","250h F Sport Performance"],
  },
  lincoln: {
    "aviator": ["Standard","Reserve","Black Label","Grand Touring","Grand Touring Reserve","Grand Touring Black Label"],
    "corsair": ["Standard","Reserve","Black Label","Grand Touring","Grand Touring Reserve","Grand Touring Black Label"],
    "nautilus": ["Standard","Reserve","Black Label"],
    "navigator": ["Standard","Reserve","Black Label","L Standard","L Reserve","L Black Label"],
  },
  mazda: {
    "cx-30": ["2.5 S","2.5 S Carbon Edition","2.5 S Select","2.5 S Preferred","2.5 S Premium","2.5 S Premium Plus","Turbo 2.5 T Carbon Edition","Turbo 2.5 T Preferred","Turbo 2.5 T Preferred Plus","Turbo 2.5 T Premium","Turbo 2.5 T Premium Plus"],
    "cx-5": ["2.5 S","2.5 S Carbon Edition","2.5 S Select","2.5 S Preferred","2.5 S Premium","2.5 S Premium Plus","Turbo 2.5 T Carbon Edition","Turbo 2.5 T Preferred","Turbo 2.5 T Premium","Turbo 2.5 T Signature"],
    "cx-50": ["2.5 S","2.5 S Select","2.5 S Preferred","2.5 S Premium","Turbo 2.5 T Premium Plus","Turbo 2.5 T Meridian Edition"],
    "cx-9": ["Sport","Touring","Carbon Edition","Grand Touring","Grand Touring Reserve","Signature"],
    "cx-90": ["3.3 Turbo Select","3.3 Turbo Preferred","3.3 Turbo Premium","3.3 Turbo Premium Plus","3.3 Turbo S Premium","3.3 Turbo S Premium Plus","PHEV Preferred","PHEV Premium","PHEV Signature"],
    "mazda3": ["2.5 S","2.5 S Carbon Edition","2.5 S Select","2.5 S Preferred","2.5 S Premium","Turbo 2.5 T Carbon Edition","Turbo 2.5 T Preferred","Turbo 2.5 T Premium Plus"],
    "mazda6": ["Sport","Touring","Carbon Edition","Grand Touring","Grand Touring Reserve","Signature"],
    "mx-5 miata": ["Sport","Club","Grand Touring","RF Club","RF Grand Touring"],
  },
  mercedes: {
    "a-class": ["A 220","A 220 4MATIC","AMG A 35"],
    "amg gt": ["53 4MATIC+","63 S E Performance","63 4MATIC+","63 S 4MATIC+","Black Series"],
    "c-class": ["C 300","C 300 4MATIC","AMG C 43","AMG C 63 S e","AMG C 63 S e Performance"],
    "e-class": ["E 350","E 350 4MATIC","E 450 4MATIC","E 450","AMG E 53","AMG E 63 S"],
    "eqs": ["450+","450 4MATIC","580 4MATIC","AMG EQS 53"],
    "eqe": ["350+","350 4MATIC","500 4MATIC","AMG EQE 43","AMG EQE 53"],
    "g-class": ["G 550","AMG G 63"],
    "gle": ["GLE 350","GLE 350 4MATIC","GLE 450 4MATIC","GLE 450e 4MATIC","GLE 580 4MATIC","AMG GLE 53","AMG GLE 63 S"],
    "glc": ["GLC 300","GLC 300 4MATIC","GLC 350e 4MATIC","AMG GLC 43","AMG GLC 63 S"],
    "gls": ["GLS 450 4MATIC","GLS 580 4MATIC","AMG GLS 63"],
    "s-class": ["S 500","S 500 4MATIC","S 580","S 580 4MATIC","AMG S 63 E Performance","Maybach S 500","Maybach S 580","Maybach S 680"],
    "sl": ["SL 43","SL 55 4MATIC+","SL 63 4MATIC+"],
  },
  nissan: {
    "altima": ["S","SR","SV","SL","Platinum","SR Midnight Edition"],
    "armada": ["S","SV","SL","Platinum","PRO-4X"],
    "frontier": ["S","SV","Pro-X","PRO-4X","SL","Long Bed S","Long Bed SV","Long Bed PRO-4X","Long Bed SL"],
    "kicks": ["S","SV","SR","SR Premium"],
    "leaf": ["S","SV Plus","SV","SL Plus"],
    "maxima": ["S","SV","SR","SR Midnight Edition","Platinum","Platinum Reserve"],
    "murano": ["S","SV","SL","Platinum"],
    "pathfinder": ["S","SV","SL","Platinum","Rock Creek"],
    "rogue": ["S","SV","SL","Platinum","Sport S","Sport SV","Sport SL"],
    "sentra": ["S","SV","SR","SR Premium"],
    "titan": ["S","SV","PRO-4X","SL","Platinum Reserve","XD S","XD SV","XD PRO-4X","XD SL","XD Platinum Reserve"],
    "versa": ["S","SR","SV"],
    "z": ["Sport","Performance","Proto Spec","NISMO"],
  },
  porsche: {
    "718 boxster": ["Base","S","GTS 4.0","Spyder","Spyder RS"],
    "718 cayman": ["Base","S","GT4","GT4 RS","GTS 4.0"],
    "911": ["Carrera","Carrera S","Carrera 4","Carrera 4S","Carrera T","Carrera GTS","4 GTS","Targa 4","Targa 4S","Targa 4 GTS","Turbo","Turbo S","GT3","GT3 RS","GT3 Touring","Dakar"],
    "cayenne": ["Base","S","GTS","Turbo","Turbo GT","E-Hybrid","S E-Hybrid","Turbo E-Hybrid","Coupe","Coupe S","Coupe GTS","Coupe Turbo","Coupe Turbo GT","Coupe E-Hybrid","Coupe Turbo E-Hybrid"],
    "macan": ["Base","S","GTS","Electric","Electric 4","Electric 4S","Electric Turbo"],
    "panamera": ["Base","4","4S","GTS","4S E-Hybrid","4 E-Hybrid","Turbo S","Turbo S E-Hybrid","Sport Turismo","Sport Turismo 4","Sport Turismo 4S","Sport Turismo GTS"],
    "taycan": ["Base","4S","GTS","Turbo","Turbo S","Cross Turismo 4","Cross Turismo 4S","Cross Turismo GTS","Cross Turismo Turbo","Sport Turismo 4","Sport Turismo 4S","Sport Turismo GTS","Sport Turismo Turbo"],
  },
  ram: {
    "1500": ["Tradesman","HFE","Express","Big Horn","Lone Star","Laramie","Rebel","Laramie Longhorn","Limited","TRX","Limited Longhorn"],
    "2500": ["Tradesman","Big Horn","Lone Star","Laramie","Power Wagon","Laramie Longhorn","Limited"],
    "3500": ["Tradesman","Big Horn","Lone Star","Laramie","Laramie Longhorn","Limited"],
    "promaster": ["1500 Low Roof","1500 High Roof","2500 High Roof","3500 High Roof","City"],
  },
  rivian: {
    "r1t": ["Standard","Adventure","Launch Edition"],
    "r1s": ["Standard","Adventure","Launch Edition"],
  },
  subaru: {
    "ascent": ["Base","Premium","Sport","Limited","Onyx Edition","Onyx Edition Limited","Touring"],
    "brz": ["Premium","Limited","tS","STI"],
    "crosstrek": ["Base","Premium","Sport","Limited","Wilderness"],
    "forester": ["Base","Premium","Sport","Limited","Touring","Wilderness"],
    "impreza": ["Base","Premium","Sport","Limited","RS"],
    "legacy": ["Base","Premium","Sport","Limited","Touring XT"],
    "outback": ["Base","Premium","Onyx Edition","Onyx Edition XT","Limited","Limited XT","Touring","Touring XT","Wilderness"],
    "solterra": ["Premium","Limited","Touring"],
    "wrx": ["Base","Premium","Limited","GT","STI","STI Limited","STI S209"],
  },
  tesla: {
    "model 3": ["Standard Range Plus","Long Range","Long Range AWD","Performance","RWD","Long Range RWD","Highland"],
    "model s": ["Plaid","Long Range"],
    "model x": ["Plaid","Long Range"],
    "model y": ["Standard Range","Long Range","Performance","RWD","Long Range AWD"],
    "cybertruck": ["Foundation Series","All-Wheel Drive","Cyberbeast"],
  },
  toyota: {
    "4runner": ["SR5","SR5 Premium","TRD Sport","TRD Off-Road","TRD Off-Road Premium","Venture Special Edition","TRD Pro","Limited","Nightshade","40th Anniversary Special Edition"],
    "avalon": ["XLE","XSE","Touring","Limited","TRD"],
    "bz4x": ["XLE","Limited"],
    "camry": ["L","LE","SE","SE Nightshade","XLE","XSE","TRD","XLE V6","XSE V6"],
    "corolla": ["L","LE","SE","SE Apex","XSE","XLE","Hatchback SE","Hatchback XSE","Cross L","Cross LE","Cross SE","Cross XSE"],
    "crown": ["XLE","Limited","Platinum"],
    "gr86": ["Base","Premium","Special Edition"],
    "gr corolla": ["Core","Circuit Edition","Morizo Edition","MATTE Edition"],
    "gr supra": ["2.0","3.0","3.0 Premium","A91-CF Edition","A91-MT Edition"],
    "highlander": ["L","LE","XLE","XSE","Limited","Platinum","Bronze Edition","Bronze Edition Hybrid","Hybrid LE","Hybrid XLE","Hybrid Limited","Hybrid Platinum"],
    "mirai": ["XLE","Limited"],
    "prius": ["LE","XLE","Limited","XLE Plug-In Hybrid","SE Plug-In Hybrid","XSE Plug-In Hybrid","Prime LE","Prime XLE","Prime SE","Prime XSE"],
    "prius prime": ["LE","SE","XSE","XSE Premium"],
    "rav4": ["LE","XLE","XLE Premium","TRD Off-Road","Adventure","Limited","Prime SE","Prime XSE","Prime XSE Premium","Hybrid LE","Hybrid XLE","Hybrid XLE Premium","Hybrid TRD Off-Road","Hybrid SE","Hybrid Limited"],
    "sequoia": ["SR5","TRD Sport","TRD Off-Road","TRD Pro","Limited","Platinum","Capstone"],
    "sienna": ["LE","XLE","XSE","Limited","Platinum","25th Anniversary Special Edition"],
    "tacoma": ["SR","SR5","TRD Sport","TRD Off-Road","Limited","TRD Pro","Trail Edition","Trailhunter"],
    "tundra": ["SR","SR5","Limited","Platinum","1794 Edition","TRD Pro","Capstone","Hybrid Limited","Hybrid Platinum","Hybrid 1794","Hybrid TRD Pro","Hybrid Capstone"],
    "venza": ["LE","XLE","Limited","Nightshade"],
  },
  volkswagen: {
    "arteon": ["SE","SEL","SEL R-Line","SEL Premium","SEL R-Line 4Motion","SEL Premium 4Motion"],
    "atlas": ["S","SE","SE Technology","SEL","SEL Premium","SEL R-Line","Cross Sport S","Cross Sport SE","Cross Sport SEL","Cross Sport SEL Premium"],
    "golf": ["S","SE","GTI S","GTI SE","GTI Autobahn","R","Golf R Lapiz Blue"],
    "id.4": ["Standard","Pro","Pro S","AWD Pro","AWD Pro S","GTX"],
    "jetta": ["S","SE","Sport","SE Sport","SEL","SEL Premium","GLI S","GLI Autobahn"],
    "taos": ["S","SE","SEL"],
    "tiguan": ["S","SE","SE R-Line Black","SEL","SEL R-Line","SEL Premium"],
  },
  volvo: {
    "c40": ["Core","Plus","Ultimate","Recharge Twin"],
    "ec40": ["Core","Plus","Ultimate"],
    "ex30": ["Core","Plus","Ultra"],
    "ex90": ["Core","Plus","Ultra"],
    "s60": ["B5 Momentum","B5 Plus","B6 Ultimate","B6 Plus Dark","Recharge T8 Plus","Recharge T8 Ultimate","Recharge T8 Plus Dark"],
    "s90": ["B6 Plus","B6 Ultimate","Recharge T8 Plus","Recharge T8 Ultimate"],
    "v60": ["B5 Momentum","B5 Plus","B6 Ultimate","Cross Country B5","Cross Country B6"],
    "v90": ["B6 Plus","Cross Country B6"],
    "xc40": ["Core","Plus","Plus Dark","Ultimate","Ultimate Dark","Recharge Core","Recharge Plus","Recharge Ultimate"],
    "xc60": ["B5 Core","B5 Plus","B5 Plus Dark","B6 Ultimate","B6 Ultimate Dark","Recharge T8 Core","Recharge T8 Plus","Recharge T8 Plus Dark","Recharge T8 Ultimate","Recharge T8 Ultimate Dark"],
    "xc90": ["B5 Core","B5 Plus","B6 Ultimate","Recharge T8 Core","Recharge T8 Plus","Recharge T8 Ultimate","Excellence"],
  },
};

export function getStaticTrims(make: string, model: string): string[] | null {
  const makeKey = make.toLowerCase().replace(/[^a-z0-9_]/g, "_").replace(/_+/g, "_");
  const modelKey = model.toLowerCase().trim();

  const makeData =
    STATIC_TRIMS[makeKey] ??
    STATIC_TRIMS[make.toLowerCase().replace(/-/g, "_")] ??
    null;

  if (!makeData) return null;

  return (
    makeData[modelKey] ??
    makeData[modelKey.replace(/-/g, " ")] ??
    makeData[modelKey.replace(/ /g, "-")] ??
    null
  );
}
